apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubeclarity.sbom-db.fullname" . }}
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{ include "kubeclarity.sbom-db.labels" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "kubeclarity.sbom-db.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "kubeclarity.sbom-db.fullname" . }}
    spec:
      serviceAccountName: {{ include "kubeclarity.sbom-db.fullname" . }}
      volumes:
        - name: tmp-volume
          emptyDir: {}
      {{- if not .Values.global.openShiftRestricted }}
      securityContext:
        fsGroup: 1000
      {{- end }}
      containers:
        - name: sbom-db
          {{- if index .Values "kubeclarity-sbom-db" "docker" "imageName" }}
          image: '{{ index .Values "kubeclarity-sbom-db" "docker" "imageName" }}'
          {{- else }}
          image: '{{ .Values.global.docker.registry }}/kubeclarity-sbom-db:{{ .Values.global.docker.tag }}'
          {{- end }}
          imagePullPolicy: {{ .Values.global.docker.imagePullPolicy }}
          args:
            - run
            - --log-level
            - {{ index .Values "kubeclarity-sbom-db" "logLevel" }}
          env:
          readinessProbe:
            httpGet:
              path: /healthz/ready
              port: 8081
            periodSeconds: 30
            failureThreshold: 5
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz/live
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 30
            failureThreshold: 5
            timeoutSeconds: 10
          securityContext:
            capabilities:
              drop:
                - all
            runAsNonRoot: true
            {{- if not .Values.global.openShiftRestricted }}
            runAsGroup: 1000
            runAsUser: 1000
            {{- end }}
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          resources:
{{- toYaml (index .Values "kubeclarity-sbom-db" "resources") | nindent 12 }}
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
{{- if index .Values "kubeclarity-sbom-db" "nodeSelector" }}
      nodeSelector:
        {{- toYaml (index .Values "kubeclarity-sbom-db" "nodeSelector") | nindent 8 }}
{{- end }}
{{- if index .Values "kubeclarity-sbom-db" "affinity" }}
      affinity:
        {{- toYaml (index .Values "kubeclarity-sbom-db" "affinity") | nindent 8 }}
{{- end }}
{{- if index .Values "kubeclarity-sbom-db" "tolerations" }}
      tolerations:
        {{- toYaml (index .Values "kubeclarity-sbom-db" "tolerations") | nindent 8 }}
{{- end }}
