run:
  skip-dirs:
    - api
    - ui
  timeout: 15m

linters-settings:
  golint:
    min-confidence: 0.1
  goimports:
    local-prefixes: github.com/openclarity/kubeclarity
  errorlint:
    # Check whether fmt.Errorf uses the %w verb for formatting errors. See the readme for caveats
    errorf: false
  gomoddirectives:
    # Allow local `replace` directives. Default is false.
    replace-local: true
    # List of allowed `replace` directives. Default is empty.
    replace-allow-list:
      # replace containerd GHSA-5ffw-gxpp-mxpf
      - github.com/containerd/containerd
      # trivy requires these replacements
      - oras.land/oras-go
      # Replace these for grype
      - github.com/CycloneDX/cyclonedx-go
      # trivy using non released version, so we need to stick on the released one for other imports that conflicts with it
      - github.com/opencontainers/image-spec

  gosec:
    # To specify a set of rules to explicitly exclude.
    # Available rules: https://github.com/securego/gosec#available-rules
#    excludes:
#      - G404 # Insecure random number source (rand)
  forbidigo:
    # Forbid the following identifiers (identifiers are written using regexp):
    forbid:
      - ^print.*$

linters:
  enable-all: true
  disable:
    - maligned
    - funlen
    - dupl
    - nestif
    - wsl
    - lll
    - interfacer
    - exhaustivestruct
    - nlreturn
    - gocritic
    - gochecknoglobals
    - testpackage
    - goerr113
    - paralleltest
    - gochecknoinits # Allow init function
    - godox # Allow TODOs
    - tagliatelle # Allow json(camel)
    - scopelint # deprecated
    - golint # deprecated
    - structcheck # deprecated
    - ifshort # deprecated
    - deadcode # deprecated
    - varcheck # deprecated
    - nolintlint # Allow nolint
    - varnamelen # Allow short var names
    - nosnakecase # Allow snake case (we are using _ in some named imports)
    - ireturn # Allow returning with iterfaces
    - exhaustruct # Allow structures with uninitialized fields
    - gci # imports still has gci lint errors after run `gci write --skip-generated -s standard -s default -s "prefix(github.com/openclarity/kubeclarity)"`

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - govet
