{{- if index .Values "kubeclarity-grype-server" "enabled" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubeclarity.grype-server.fullname" . }}
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{ include "kubeclarity.grype-server.labels" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "kubeclarity.grype-server.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "kubeclarity.grype-server.fullname" . }}
    spec:
      serviceAccountName: {{ include "kubeclarity.grype-server.fullname" . }}
      volumes:
        - name: tmp-volume
          emptyDir: {}
      {{- if not .Values.global.openShiftRestricted }}
      securityContext:
        fsGroup: 1000
      {{- end }}
      containers:
        - name: grype-server
          image: '{{ index .Values "kubeclarity-grype-server" "docker" "imageRepo" }}/grype-server:{{ index .Values "kubeclarity-grype-server" "docker" "imageTag" }}'
          imagePullPolicy: {{ index .Values "kubeclarity-grype-server" "docker" "imagePullPolicy" }}
          args:
            - run
            - --log-level
            - {{ index .Values "kubeclarity-grype-server" "logLevel" }}
          env:
            - name: DB_ROOT_DIR
              value: /tmp/
{{- if index .Values "kubeclarity-runtime-scan" "httpsProxy" }}
            - name: HTTPS_PROXY
              value: {{ index .Values "kubeclarity-runtime-scan" "httpsProxy" }}
{{- end}}
{{- if index .Values "kubeclarity-runtime-scan" "httpProxy" }}
            - name: HTTP_PROXY
              value: {{ index .Values "kubeclarity-runtime-scan" "httpProxy" }}
{{- end}}
          readinessProbe:
            httpGet:
              path: /healthz/ready
              port: 8080
            periodSeconds: 30
            failureThreshold: 5
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz/live
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
            failureThreshold: 5
            timeoutSeconds: 10
          securityContext:
            capabilities:
              drop:
                - all
            runAsNonRoot: true
            {{- if not .Values.global.openShiftRestricted }}
            runAsGroup: 1000
            runAsUser: 1000
            {{- end }}
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          resources:
{{- toYaml (index .Values "kubeclarity-grype-server" "resources") | nindent 12 }}
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
{{- end}}
{{- if index .Values "kubeclarity-grype-server" "nodeSelector" }}
      nodeSelector:
        {{- toYaml (index .Values "kubeclarity-grype-server" "nodeSelector") | nindent 8 }}
{{- end }}
{{- if index .Values "kubeclarity-grype-server" "affinity" }}
      affinity:
        {{- toYaml (index .Values "kubeclarity-grype-server" "affinity") | nindent 8 }}
{{- end }}
{{- if index .Values "kubeclarity-grype-server" "tolerations" }}
      tolerations:
        {{- toYaml (index .Values "kubeclarity-grype-server" "tolerations") | nindent 8 }}
{{- end }}
