apiVersion: v1
kind: ServiceAccount
metadata:
  name: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccountName: test
      containers:
        - name: nginx
          image: nginx@sha256:859ab6768a6f26a79bc42b231664111317d095a4f04e4b6fe79ce37b3d199097 # nginx:1.21.6
          command: ["/bin/sleep", "10000000"]
          imagePullPolicy: IfNotPresent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl-scheme1-cant-scan
spec:
  selector:
    matchLabels:
      app: curl
  replicas: 1
  template:
    metadata:
      labels:
        app: curl
    spec:
      serviceAccountName: test
      containers:
        - name: curl
          image: radial/busyboxplus:curl
          command: ["/bin/sleep", "10000000"]
          imagePullPolicy: IfNotPresent
---
