name: Release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  packages: write
  contents: write

env:
  GO_VERSION: 1.19

jobs:
  verification:
    name: Verification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Check licenses
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make license-check

      - name: Run verification
        run: make check

  build_and_push:
    needs: verification
    name: Build & Push
    uses: ./.github/workflows/reusable-build-and-push.yml
    with:
      image_tag: ${{ github.ref_name }}
      push: true
      upload: false

  release:
    needs: build_and_push
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: v0.178.0
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  helm_release:
    needs: release
    name: Publish Helm Chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Replace release version
        id: replace_version
        run: |
          sed -i 's/v0.0.0-dev/${{ github.ref_name }}/g' charts/kubeclarity/Chart.yaml
          sed -i 's/latest/${{ github.ref_name }}/g' charts/kubeclarity/values.yaml

      - name: Set up Helm
        uses: azure/setup-helm@v3.5
        with:
          version: v3.8.1

      - uses: actions/setup-python@v4.7.0
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.4.0

      - name: Add Bitnami Repository
        run: helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Add Aqua Security Repository
        run: helm repo add aquasecurity https://aquasecurity.github.io/helm-charts

      - name: Run chart-testing (lint)
        run: ct lint --debug --config charts/testing.yaml

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
          charts_dir: charts
          config: charts/cr.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
