name: CI
on:
  merge_group:
  pull_request:
    paths:
      - '**.md'

jobs:
  verification:
    name: Verification
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No verification required"'

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required"'

  e2e:
    name: E2E
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No E2E required"'

  lint_chart:
    name: Lint Helm Chart
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No lint required"'
